const airportNames = {
  "CPH": "Copenhagen Airport",
  "TRN": "Turin Airport",
  "MXP": "Milan Malpensa Airport",
  "BGY": "Orio al Serio International Airport",
  "PMO": "Palermo Airport",
  "CTA": "Catania Fontanarossa Airport",
  "FCO": "Rome Fiumicino Airport",
  "LIN": "Milan Linate Airport",
  "BLQ": "Bologna Guglielmo Marconi Airport",
  "VCE": "Venice Marco Polo Airport",
  "NAP": "Naples International Airport",
  "FLR": "Florence Airport",
  "BRI": "Bari Karol Wojtyla Airport",
  "VRN": "Verona Villafranca Airport",
  "GOA": "Genoa Cristoforo Colombo Airport",
  "OLB": "Olbia Costa Smeralda Airport",
  "AOI": "Ancona Falconara Airport",
  "LHR": "London Heathrow Airport",
  "CDG": "Charles de Gaulle Airport",
  "AMS": "Amsterdam Schiphol Airport",
  "FRA": "Frankfurt Airport",
  "MAD": "Adolfo Suárez Madrid–Barajas Airport",
  "BCN": "Barcelona–El Prat Airport",
  "LGW": "London Gatwick Airport",
  "MUC": "Munich Airport",
  "SVO": "Sheremetyevo International Airport",
  "VIE": "Vienna International Airport",
  "DUB": "Dublin Airport",
  "ARN": "Stockholm Arlanda Airport",
  "ZRH": "Zurich Airport",
  "BRU": "Brussels Airport",
  "OSL": "Oslo Gardermoen Airport",
  "ATH": "Athens International Airport",
  "HEL": "Helsinki Airport",
  "BUD": "Budapest Ferenc Liszt International Airport",
  "WAW": "Warsaw Chopin Airport",
  "PRG": "Václav Havel Airport Prague",
  "LIS": "Lisbon Airport",
  "EDI": "Edinburgh Airport",
  "MAN": "Manchester Airport",
  "BFS": "Belfast International Airport",
  "HAM": "Hamburg Airport",
  "STN": "London Stansted Airport",
  "GLA": "Glasgow Airport",
  "DUS": "Düsseldorf Airport",
  "LYS": "Lyon–Saint-Exupéry Airport",
  "NCE": "Nice Côte d'Azur Airport",
  "BSL": "EuroAirport Basel-Mulhouse-Freiburg",
  "RIX": "Riga International Airport",
  "LAX": "Los Angeles International Airport",
  "JFK": "John F. Kennedy International Airport",
  "HND": "Tokyo Haneda Airport",
  "SIN": "Singapore Changi Airport",
  "SYD": "Sydney Kingsford Smith Airport",
  "DXB": "Dubai International Airport",
  "HKG": "Hong Kong International Airport",
  "ORD": "O'Hare International Airport",
  "YYZ": "Toronto Pearson International Airport",
  "GRU": "São Paulo/Guarulhos International Airport",
  "ATL": "Hartsfield-Jackson Atlanta International Airport",
  "PEK": "Beijing Capital International Airport",
  "ICN": "Incheon International Airport",
  "NRT": "Narita International Airport",
  "BKK": "Suvarnabhumi Airport",
  "KUL": "Kuala Lumpur International Airport",
  "DME": "Domodedovo International Airport",
  "MEL": "Melbourne Airport",
  "JNB": "O. R. Tambo International Airport",
  "EZE": "Ministro Pistarini International Airport",
  "GIG": "Rio de Janeiro–Galeão International Airport",
  "BNE": "Brisbane Airport",
  "IST": "Istanbul Airport",
  "SEA": "Seattle-Tacoma International Airport",
  "MEX": "Mexico City International Airport",
  "SCL": "Comodoro Arturo Merino Benítez International Airport",
  "CPT": "Cape Town International Airport",
  "MNL": "Ninoy Aquino International Airport",
  "BOM": "Chhatrapati Shivaji Maharaj International Airport",
  "DEL": "Indira Gandhi International Airport",
  "GVA": "Geneva Airport",
  "MCO": "Orlando International Airport",
  "HNL": "Daniel K. Inouye International Airport"
};

const airportTokens = {
  "CPH": "eyJlIjoiOTU2NzM1MTkiLCJzIjoiQ1BIIiwiaCI6IjI3NTM5OTAyIiwidCI6IkFJUlBPUlQifQ==",
  "TRN": "eyJlIjoiOTU2NzM1ODAiLCJzIjoiVFJOIiwiaCI6IjI3NTQ3MjQ4IiwidCI6IkFJUlBPUlQifQ==", 
  "MXP": "eyJlIjoiOTU1NjUwNzAiLCJzIjoiTVhQIiwiaCI6IjI3NTQ0MDY4IiwidCI6IkFJUlBPUlQifQ==", 
  "BGY": "eyJlIjoiOTY3MjM2NTMiLCJzIjoiQkdZIiwiaCI6IjI4NTQ3MzEzIiwidCI6IkFJUlBPUlQifQ==",
  "PMO": "eyJlIjoiOTU2NzM2NDciLCJzIjoiUE1PIiwiaCI6IjI3NTQ1OTg5IiwidCI6IkFJUlBPUlQifQ==",
  "CTA": "eyJlIjoiOTU2NzM4OTMiLCJzIjoiQ1RBIiwiaCI6IjI3NTQwNTYyIiwidCI6IkFJUlBPUlQifQ==",
  "FCO": "eyJlIjoiOTY3MjM2MjYiLCJzIjoiRkNPIiwiaCI6IjI4NTQ3MjgzIiwidCI6IkFJUlBPUlQifQ==",
  "LIN": "eyJlIjoiOTY3MjM2NTAiLCJzIjoiTElOIiwiaCI6IjI4NTQ3MzEwIiwidCI6IkFJUlBPUlQifQ==",
  "BLQ": "eyJlIjoiOTY3MjM2NTEiLCJzIjoiQkxRIiwiaCI6IjI4NTQ3MzExIiwidCI6IkFJUlBPUlQifQ==",
  "VCE": "eyJlIjoiOTY3MjM2NTIiLCJzIjoiVkNFIiwiaCI6IjI4NTQ3MzEyIiwidCI6IkFJUlBPUlQifQ==",
  "NAP": "eyJlIjoiOTY3MjM2NTMiLCJzIjoiTkFQIiwiaCI6IjI4NTQ3MzEzIiwidCI6IkFJUlBPUlQifQ==",
  "FLR": "eyJlIjoiOTY3MjM2NDgiLCJzIjoiRkxSIiwiaCI6IjI4NTQ3MzEwIiwidCI6IkFJUlBPUlQifQ==",
  "BRI": "eyJlIjoiOTY3MjM2NDkiLCJzIjoiQlJJLCIsIHRlc3QiOiAiVEVTVCJ9",
  "VRN": "eyJlIjoiOTY3MjM2NTAiLCJzIjoiVlJOLCIsIHRlc3QiOiAiVEVTVCJ9",
  "GOA": "eyJlIjoiOTY3MjM2NTEiLCJzIjoiR09BIiwiaCI6IjI4NTQ3MzEwIiwidCI6IkFJUlBPUlQifQ==",
  "OLB": "eyJlIjoiOTY3MjM2NTIiLCJzIjoiT0xCIiwiaCI6IjI4NTQ3MzEyIiwidCI6IkFJUlBPUlQifQ==",
  "AOI": "eyJlIjoiOTY3MjM2NTMiLCJzIjoiQU9JIiwiaCI6IjI4NTQ3MzEzIiwidCI6IkFJUlBPUlQifQ==",
  "LHR": "eyJlIjoiOTY3MjM2MDYiLCJzIjoiTEhSIiwiaCI6IjI4NTQ3MjYzIiwidCI6IkFJUlBPUlQifQ==",
  "CDG": "eyJlIjoiOTY3MjM1OTgiLCJzIjoiQ0RHIiwiaCI6IjI4NTQ3MjU2IiwidCI6IkFJUlBPUlQifQ==",
  "AMS": "eyJlIjoiOTY3MjM2MDQiLCJzIjoiQU1TIiwiaCI6IjI4NTQ3MjYxIiwidCI6IkFJUlBPUlQifQ==",
  "FRA": "eyJlIjoiOTY3MjM2MDUiLCJzIjoiRlJBIiwiaCI6IjI4NTQ3MjYyIiwidCI6IkFJUlBPUlQifQ==",
  "MAD": "eyJlIjoiOTY3MjM2MjAiLCJzIjoiTUFEIiwiaCI6IjI4NTQ3Mjc3IiwidCI6IkFJUlBPUlQifQ==",
  "BCN": "eyJlIjoiOTY3MjM2MTgiLCJzIjoiQkNOIiwiaCI6IjI4NTQ3Mjc1IiwidCI6IkFJUlBPUlQifQ==",
  "LGW": "eyJlIjoiOTY3MjM2MjIiLCJzIjoiTEdXIiwiaCI6IjI4NTQ3Mjc5IiwidCI6IkFJUlBPUlQifQ==",
  "MUC": "eyJlIjoiOTY3MjM2MjEiLCJzIjoiTVVDIiwiaCI6IjI4NTQ3Mjc4IiwidCI6IkFJUlBPUlQifQ==",
  "SVO": "eyJlIjoiOTY3MjM2MjUiLCJzIjoiU1ZPIiwiaCI6IjI4NTQ3MjgyIiwidCI6IkFJUlBPUlQifQ==",
  "VIE": "eyJlIjoiOTY3MjM2NTgiLCJzIjoiVklFIiwiaCI6IjI4NTQ3MzE1IiwidCI6IkFJUlBPUlQifQ==",
  "DUB": "eyJlIjoiOTY3MjM2NTkiLCJzIjoiRFVCIiwiaCI6IjI4NTQ3MzE2IiwidCI6IkFJUlBPUlQifQ==",
  "ARN": "eyJlIjoiOTY3MjM2MjciLCJzIjoiQVJOLCIsIHRlc3QiOiAiVEVTVCJ9",
  "ZRH": "eyJlIjoiOTY3MjM2MTkiLCJzIjoiWlJIIiwiaCI6IjI4NTQ3Mjc2IiwidCI6IkFJUlBPUlQifQ==",
  "BRU": "eyJlIjoiOTY3MjM2NjAiLCJzIjoiQlJVLCIsIHRlc3QiOiAiVEVTVCJ9",
  "OSL": "eyJlIjoiOTY3MjM2NjEiLCJzIjoiT1NMIiwiaCI6IjI4NTQ3MzE3IiwidCI6IkFJUlBPUlQifQ==",
  "ATH": "eyJlIjoiOTY3MjM2NjIiLCJzIjoiQVRIIiwiaCI6IjI4NTQ3MzE4IiwidCI6IkFJUlBPUlQifQ==",
  "HEL": "eyJlIjoiOTY3MjM2NjMiLCJzIjoiSEVNIiwiaCI6IjI4NTQ3MzE5IiwidCI6IkFJUlBPUlQifQ==",
  "BUD": "eyJlIjoiOTY3MjM2NjQiLCJzIjoiQlVEIiwiaCI6IjI4NTQ3MzIwIiwidCI6IkFJUlBPUlQifQ==",
  "WAW": "eyJlIjoiOTY3MjM2NjUiLCJzIjoiV0FXIiwiaCI6IjI4NTQ3MzIxIiwidCI6IkFJUlBPUlQifQ==",
  "PRG": "eyJlIjoiOTY3MjM2NjYiLCJzIjoiUFJHIiwiaCI6IjI4NTQ3MzIyIiwidCI6IkFJUlBPUlQifQ==",
  "LIS": "eyJlIjoiOTY3MjM2NjciLCJzIjoiTElTIiwiaCI6IjI4NTQ3MzIzIiwidCI6IkFJUlBPUlQifQ==",
  "EDI": "eyJlIjoiOTY3MjM2NjgiLCJzIjoiRURJIiwiaCI6IjI4NTQ3MzI0IiwidCI6IkFJUlBPUlQifQ==",
  "MAN": "eyJlIjoiOTY3MjM2NjkiLCJzIjoiTUFOLCIsIHRlc3QiOiAiVEVTVCJ9",
  "BFS": "eyJlIjoiOTY3MjM2NzAiLCJzIjoiQkZTIiwiaCI6IjI4NTQ3MzI2IiwidCI6IkFJUlBPUlQifQ==",
  "HAM": "eyJlIjoiOTY3MjM2NzEiLCJzIjoiSEFNIiwiaCI6IjI4NTQ3MzI3IiwidCI6IkFJUlBPUlQifQ==",
  "STN": "eyJlIjoiOTY3MjM2NzIiLCJzIjoiU1ROIiwiaCI6IjI4NTQ3MzI4IiwidCI6IkFJUlBPUlQifQ==",
  "GLA": "eyJlIjoiOTY3MjM2NzMiLCJzIjoiR0xBIiwiaCI6IjI4NTQ3MzI5IiwidCI6IkFJUlBPUlQifQ==",
  "DUS": "eyJlIjoiOTY3MjM2NzQiLCJzIjoiRFVTIiwiaCI6IjI4NTQ3MzMwIiwidCI6IkFJUlBPUlQifQ==",
  "LYS": "eyJlIjoiOTY3MjM2NzUiLCJzIjoiTFlTIiwiaCI6IjI4NTQ3MzMxIiwidCI6IkFJUlBPUlQifQ==",
  "NCE": "eyJlIjoiOTY3MjM2NzYiLCJzIjoiTkNFIiwiaCI6IjI4NTQ3MzMyIiwidCI6IkFJUlBPUlQifQ==",
  "BSL": "eyJlIjoiOTY3MjM2NzciLCJzIjoiQlNMIiwiaCI6IjI4NTQ3MzMzIiwidCI6IkFJUlBPUlQifQ==",
  "RIX": "eyJlIjoiOTY3MjM2NzgiLCJzIjoiUklYIiwiaCI6IjI4NTQ3MzM0IiwidCI6IkFJUlBPUlQifQ==",
  "LAX": "eyJlIjoiOTY3MjM1ODAiLCJzIjoiTEFYIiwiaCI6IjI4NTQ3MjQ4IiwidCI6IkFJUlBPUlQifQ==",
  "JFK": "eyJlIjoiOTY3MjM1ODgiLCJzIjoiSkZLIiwiaCI6IjI4NTQ3MjU4IiwidCI6IkFJUlBPUlQifQ==",
  "HND": "eyJlIjoiOTY3MjM1OTciLCJzIjoiSE5EIiwiaCI6IjI4NTQ3MjU2IiwidCI6IkFJUlBPUlQifQ==",
  "CDG": "eyJlIjoiOTY3MjM1OTgiLCJzIjoiQ0RHIiwiaCI6IjI4NTQ3MjU2IiwidCI6IkFJUlBPUlQifQ==",
  "SIN": "eyJlIjoiOTY3MjM2MDAiLCJzIjoiU0lOIiwiaCI6IjI4NTQ3MjU3IiwidCI6IkFJUlBPUlQifQ==",
  "SYD": "eyJlIjoiOTY3MjM2MDEiLCJzIjoiU1lEIiwiaCI6IjI4NTQ3MjU4IiwidCI6IkFJUlBPUlQifQ==",
  "DXB": "eyJlIjoiOTY3MjM2MDIiLCJzIjoiRFhCIiwiaCI6IjI4NTQ3MjU5IiwidCI6IkFJUlBPUlQifQ==",
  "HKG": "eyJlIjoiOTY3MjM2MDMiLCJzIjoiSEtHIiwiaCI6IjI4NTQ3MjYwIiwidCI6IkFJUlBPUlQifQ==",
  "AMS": "eyJlIjoiOTY3MjM2MDQiLCJzIjoiQU1TIiwiaCI6IjI4NTQ3MjYxIiwidCI6IkFJUlBPUlQifQ==",
  "FRA": "eyJlIjoiOTY3MjM2MDUiLCJzIjoiRlJBIiwiaCI6IjI4NTQ3MjYyIiwidCI6IkFJUlBPUlQifQ==",
  "LHR": "eyJlIjoiOTY3MjM2MDYiLCJzIjoiTEhSIiwiaCI6IjI4NTQ3MjYzIiwidCI6IkFJUlBPUlQifQ==",
  "ORD": "eyJlIjoiOTY3MjM2MDciLCJzIjoiT1JEIiwiaCI6IjI4NTQ3MjY0IiwidCI6IkFJUlBPUlQifQ==",
  "YYZ": "eyJlIjoiOTY3MjM2MDgiLCJzIjoiWVlWIiwiaCI6IjI4NTQ3MjY1IiwidCI6IkFJUlBPUlQifQ==",
  "GRU": "eyJlIjoiOTY3MjM2MDkiLCJzIjoiR1JVIiwiaCI6IjI4NTQ3MjY2IiwidCI6IkFJUlBPUlQifQ==",
  "ATL": "eyJlIjoiOTY3MjM2MTAiLCJzIjoiQVRMIiwiaCI6IjI4NTQ3MjY3IiwidCI6IkFJUlBPUlQifQ==",
  "PEK": "eyJlIjoiOTY3MjM2MTEiLCJzIjoiUEVLIiwiaCI6IjI4NTQ3MjY4IiwidCI6IkFJUlBPUlQifQ==",
  "ICN": "eyJlIjoiOTY3MjM2MTIiLCJzIjoiSUNOIiwiaCI6IjI4NTQ3MjY5IiwidCI6IkFJUlBPUlQifQ==",
  "NRT": "eyJlIjoiOTY3MjM2MTMiLCJzIjoiTlJUIiwiaCI6IjI4NTQ3MjcwIiwidCI6IkFJUlBPUlQifQ==",
  "BKK": "eyJlIjoiOTY3MjM2MTQiLCJzIjoiQktLIiwiaCI6IjI4NTQ3MjcxIiwidCI6IkFJUlBPUlQifQ==",
  "KUL": "eyJlIjoiOTY3MjM2MTUiLCJzIjoiS1VMIiwiaCI6IjI4NTQ3MjcyIiwidCI6IkFJUlBPUlQifQ==",
  "DME": "eyJlIjoiOTY3MjM2MTYiLCJzIjoiRE1FIiwiaCI6IjI4NTQ3MjczIiwidCI6IkFJUlBPUlQifQ==",
  "MEL": "eyJlIjoiOTY3MjM2MTciLCJzIjoiTUVMIiwiaCI6IjI4NTQ3Mjc0IiwidCI6IkFJUlBPUlQifQ==",
  "BCN": "eyJlIjoiOTY3MjM2MTgiLCJzIjoiQkNOIiwiaCI6IjI4NTQ3Mjc1IiwidCI6IkFJUlBPUlQifQ==",
  "ZRH": "eyJlIjoiOTY3MjM2MTkiLCJzIjoiWlJIIiwiaCI6IjI4NTQ3Mjc2IiwidCI6IkFJUlBPUlQifQ==",
  "MAD": "eyJlIjoiOTY3MjM2MjAiLCJzIjoiTUFEIiwiaCI6IjI4NTQ3Mjc3IiwidCI6IkFJUlBPUlQifQ==",
  "MUC": "eyJlIjoiOTY3MjM2MjEiLCJzIjoiTVVDIiwiaCI6IjI4NTQ3Mjc4IiwidCI6IkFJUlBPUlQifQ==",
  "LGW": "eyJlIjoiOTY3MjM2MjIiLCJzIjoiTEdXIiwiaCI6IjI4NTQ3Mjc5IiwidCI6IkFJUlBPUlQifQ==",
  "JNB": "eyJlIjoiOTY3MjM2MjMiLCJzIjoiSk5CIiwiaCI6IjI4NTQ3MjgwIiwidCI6IkFJUlBPUlQifQ==",
  "EZE": "eyJlIjoiOTY3MjM2MjQiLCJzIjoiRVpFIiwiaCI6IjI4NTQ3MjgxIiwidCI6IkFJUlBPUlQifQ==",
  "SVO": "eyJlIjoiOTY3MjM2MjUiLCJzIjoiU1ZPIiwiaCI6IjI4NTQ3MjgyIiwidCI6IkFJUlBPUlQifQ==",
  "ARN": "eyJlIjoiOTY3MjM2MjciLCJzIjoiQVJOIiwiaCI6IjI4NTQ3Mjg0IiwidCI6IkFJUlBPUlQifQ==",
  "GIG": "eyJlIjoiOTY3MjM2MjgiLCJzIjoiR0lHIiwiaCI6IjI4NTQ3Mjg1IiwidCI6IkFJUlBPUlQifQ==",
  "DUB": "eyJlIjoiOTY3MjM2MjkiLCJzIjoiRFVCIiwiaCI6IjI4NTQ3Mjg2IiwidCI6IkFJUlBPUlQifQ==",
  "ATH": "eyJlIjoiOTY3MjM2MzAiLCJzIjoiQVRIIiwiaCI6IjI4NTQ3Mjg3IiwidCI6IkFJUlBPUlQifQ==",
  "BNE": "eyJlIjoiOTY3MjM2MzEiLCJzIjoiQk5FIiwiaCI6IjI4NTQ3Mjg4IiwidCI6IkFJUlBPUlQifQ==",
  "IST": "eyJlIjoiOTY3MjM2MzIiLCJzIjoiSVNUIiwiaCI6IjI4NTQ3Mjg5IiwidCI6IkFJUlBPUlQifQ==",
  "SEA": "eyJlIjoiOTY3MjM2MzMiLCJzIjoiU0VBIiwiaCI6IjI4NTQ3MjkwIiwidCI6IkFJUlBPUlQifQ==",
  "MEX": "eyJlIjoiOTY3MjM2MzQiLCJzIjoiTUVYIiwiaCI6IjI4NTQ3MjkxIiwidCI6IkFJUlBPUlQifQ==",
  "DUS": "eyJlIjoiOTY3MjM2MzUiLCJzIjoiRFVTIiwiaCI6IjI4NTQ3MjkyIiwidCI6IkFJUlBPUlQifQ==",
  "SCL": "eyJlIjoiOTY3MjM2MzYiLCJzIjoiU0NMIiwiaCI6IjI4NTQ3MjkzIiwidCI6IkFJUlBPUlQifQ==",
  "CPT": "eyJlIjoiOTY3MjM2MzciLCJzIjoiQ1BUIiwiaCI6IjI4NTQ3Mjk0IiwidCI6IkFJUlBPUlQifQ==",
  "MNL": "eyJlIjoiOTY3MjM2MzgiLCJzIjoiTU5MIiwiaCI6IjI4NTQ3Mjk1IiwidCI6IkFJUlBPUlQifQ==",
  "BOM": "eyJlIjoiOTY3MjM2MzkiLCJzIjoiQk9NIiwiaCI6IjI4NTQ3Mjk2IiwidCI6IkFJUlBPUlQifQ==",
  "DEL": "eyJlIjoiOTY3MjM2NDAiLCJzIjoiREVMIiwiaCI6IjI4NTQ3Mjk3IiwidCI6IkFJUlBPUlQifQ==",
  "GVA": "eyJlIjoiOTY3MjM2NDEiLCJzIjoiR1ZBIiwiaCI6IjI4NTQ3Mjk4IiwidCI6IkFJUlBPUlQifQ==",
  "LIS": "eyJlIjoiOTY3MjM2NDIiLCJzIjoiTElTIiwiaCI6IjI4NTQ3Mjk5IiwidCI6IkFJUlBPUlQifQ==",
  "HEL": "eyJlIjoiOTY3MjM2NDMiLCJzIjoiSEVMIiwiaCI6IjI4NTQ3MzAwIiwidCI6IkFJUlBPUlQifQ==",
  "OSL": "eyJlIjoiOTY3MjM2NDQiLCJzIjoiT1NMIiwiaCI6IjI4NTQ3MzAxIiwidCI6IkFJUlBPUlQifQ==",
  "BUD": "eyJlIjoiOTY3MjM2NDUiLCJzIjoiQlVEIiwiaCI6IjI4NTQ3MzAyIiwidCI6IkFJUlBPUlQifQ==",
  "PRG": "eyJlIjoiOTY3MjM2NDYiLCJzIjoiUFJHIiwiaCI6IjI4NTQ3MzAzIiwidCI6IkFJUlBPUlQifQ==",
  "MCO": "eyJlIjoiOTY3MjM2NDciLCJzIjoiTUNPIiwiaCI6IjI4NTQ3MzA0IiwidCI6IkFJUlBPUlQifQ==",
  "HNL": "eyJlIjoiOTY3MjM2NDgiLCJzIjoiSE5MIiwiaCI6IjI4NTQ3MzA1IiwidCI6IkFJUlBPUlQifQ==",
  "TLV": "eyJlIjoiOTY3MjM2NDkiLCJzIjoiVExWIiwiaCI6IjI4NTQ3MzA2IiwidCI6IkFJUlBPUlQifQ==",
  "YVR": "eyJlIjoiOTY3MjM2NTAiLCJzIjoiWVZSIiwiaCI6IjI4NTQ3MzA3IiwidCI6IkFJUlBPUlQifQ==",
  "TPE": "eyJlIjoiOTY3MjM2NTEiLCJzIjoiVFBFIiwiaCI6IjI4NTQ3MzA4IiwidCI6IkFJUlBPUlQifQ==",
  "CGK": "eyJlIjoiOTY3MjM2NTIiLCJzIjoiQ0dLIiwiaCI6IjI4NTQ3MzA5IiwidCI6IkFJUlBPUlQifQ==",
  "SZX": "eyJlIjoiOTY3MjM2NTMiLCJzIjoiU1pYIiwiaCI6IjI4NTQ3MzEwIiwidCI6IkFJUlBPUlQifQ==",
  "BOG": "eyJlIjoiOTY3MjM2NTQiLCJzIjoiQk9HIiwiaCI6IjI4NTQ3MzExIiwidCI6IkFJUlBPUlQifQ==",
  "CUN": "eyJlIjoiOTY3MjM2NTUiLCJzIjoiQ1VNIiwiaCI6IjI4NTQ3MzEyIiwidCI6IkFJUlBPUlQifQ==",
  "SFO": "eyJlIjoiOTY3MjM2NTYiLCJzIjoiU0ZPIiwiaCI6IjI4NTQ3MzEzIiwidCI6IkFJUlBPUlQifQ==",
  "MSP": "eyJlIjoiOTY3MjM2NTciLCJzIjoiTVNQIiwiaCI6IjI4NTQ3MzE0IiwidCI6IkFJUlBPUlQifQ==",
  "IAD": "eyJlIjoiOTY3MjM2NTgiLCJzIjoiSUFEIiwiaCI6IjI4NTQ3MzE1IiwidCI6IkFJUlBPUlQifQ==",
  "DTW": "eyJlIjoiOTY3MjM2NTkiLCJzIjoiRFRTIiwiaCI6IjI4NTQ3MzE2IiwidCI6IkFJUlBPUlQifQ=="
};